# -*- coding: utf-8 -*-
"""
pepper_guess_game.py  --  "Guess What" riddle game for Pepper (EN / DE)

Pepper secretly picks an animal, country or city and describes it without
naming it. The children guess out loud. There is a HINT button on the tablet;
tapping it (or saying "hint" / "Tipp") makes Pepper give the next clue. After a
correct guess (or a few tries) Pepper reveals the answer and moves on.

The clue and the hints are generated by the HCTL chat model, so the game works
in both English and German. Guesses are judged by the same model, so German
answers (e.g. "Frankreich" for France) are accepted too.

Runs in the Python 2.7 (32-bit) 'pepper' conda env. Token in HCTL_TOKEN.

Examples:
    python pepper_guess_game.py -l en
    python pepper_guess_game.py -l de -c animals
"""

import os
import re
import sys
import json
import time
import random
import argparse
import subprocess

import qi
import requests

from pepper_echo import (record_audio, download_audio, transcribe,
                         STT_BASE_URL, BASE_URL_ENV_VAR, TOKEN_ENV_VAR,
                         PEPPER_PW_ENV_VAR)
from pepper_parrot_game import (find_pepper, show_on_tablet, set_eyes, _esc,
                                read_mem_int, STOP_KEY, EXIT_KEY,
                                NAOQI_PORT, HOTSPOT_SUBNET)
from pepper_qa_game import CHAT_API_URL, CHAT_MODEL

HINT_KEY = 'Pepper/Guess/HintReq'   # tablet HINT button writes here
SKIP_KEY = 'Pepper/Guess/SkipReq'   # tablet SKIP button writes here
# STOP_KEY / EXIT_KEY are shared across all games (imported above)
REMOTE_HTML = '/home/nao/.local/share/PackageManager/apps/robot-page/html/guess.html'

# English canonical secrets; the model describes/judges them in the chosen
# language, so German names (Frankreich, Pinguin, ...) are accepted as correct.
WORDS = {
    'animals':   ['lion', 'elephant', 'penguin', 'kangaroo', 'dolphin', 'giraffe',
                  'owl', 'octopus', 'bee', 'horse', 'tiger', 'monkey', 'rabbit',
                  'snake', 'frog'],
    'countries': ['France', 'Japan', 'Egypt', 'Brazil', 'Italy', 'Kenya', 'India',
                  'Norway', 'Australia', 'Turkey', 'Germany', 'Spain', 'China',
                  'Canada', 'Greece'],
    'cities':    ['Paris', 'London', 'Rome', 'Tokyo', 'Berlin', 'Istanbul', 'Venice',
                  'Munich', 'Cairo', 'Amsterdam', 'Vienna', 'Barcelona', 'Athens'],
}

PHRASES = {
    'en': {
        'tts': 'English',
        'catname': {'animals': 'an animal', 'countries': 'a country', 'cities': 'a city'},
        'cattab':  {'animals': 'ANIMAL', 'countries': 'COUNTRY', 'cities': 'CITY'},
        'welcome': "Let's play the guessing game! I will describe something and you guess what it is.",
        'think': 'Let me think of something.',
        'guess_now': 'What is your guess?',
        'tab_main': 'Guess what it is!',
        'hint_btn': 'HINT',
        'skip_btn': 'SKIP',
        'stop_btn': 'STOP',
        'exit_btn': 'MENU',
        'hint_intro': "Here is a hint.",
        'no_more_hints': 'That was my last hint!',
        'wrong': "Not quite! Try again, tap for a hint, or skip.",
        'correct': "Yes! Well done!",
        'skip_intro': "No problem, let's move on.",
        'reveal': "It was %s.",
        'nothing': "Sorry, I could not hear you. Please say your guess again.",
        'hintwords': ['hint', 'clue', 'help'],
        'skipwords': ['skip', 'pass', 'give up', 'next one'],
        'goodbye': 'Great guessing! See you next time.',
    },
    'de': {
        'tts': 'German',
        'catname': {'animals': 'ein Tier', 'countries': 'ein Land', 'cities': 'eine Stadt'},
        'cattab':  {'animals': 'TIER', 'countries': 'LAND', 'cities': 'STADT'},
        'welcome': 'Lass uns das Ratespiel spielen! Ich beschreibe etwas und du raetst, was es ist.',
        'think': 'Lass mich ueberlegen.',
        'guess_now': 'Was ist deine Vermutung?',
        'tab_main': 'Rate, was es ist!',
        'hint_btn': 'TIPP',
        'skip_btn': 'WEITER',
        'stop_btn': 'STOPP',
        'exit_btn': 'MENU',
        'hint_intro': 'Hier ist ein Tipp.',
        'no_more_hints': 'Das war mein letzter Tipp!',
        'wrong': 'Nicht ganz! Versuch es nochmal, tippe fuer einen Tipp, oder weiter.',
        'correct': 'Ja! Sehr gut!',
        'skip_intro': 'Kein Problem, machen wir weiter.',
        'reveal': 'Es war %s.',
        'nothing': 'Entschuldigung, ich konnte dich nicht hoeren. Sag deine Vermutung bitte nochmal.',
        'hintwords': ['tipp', 'hinweis', 'hilfe'],
        'skipwords': ['weiter', 'aufgeben', 'keine ahnung'],
        'goodbye': 'Tolles Raten! Bis zum naechsten Mal.',
    },
}


def relaunch_kiosk_menu(ip):
    """Spawn the tablet menu (kiosk) so the player returns to game selection.

    Called when the tablet EXIT button was tapped and this game was NOT
    already launched by the kiosk (e.g. started directly from the PC admin
    panel) -- otherwise nothing would bring the game-picker screen back, so
    this game brings it back itself before it exits. Skipped when the kiosk
    IS the parent (args.kiosk), since it already re-shows the menu on its
    own once this process ends.
    """
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        cmd = [sys.executable, os.path.join(here, 'pepper_kiosk.py'), '-ip', ip]
        subprocess.Popen(cmd, cwd=here)
    except Exception as err:
        print('could not bring back the tablet menu (%s)' % err)


def chat(messages, token, max_tokens=600, temperature=0.7):
    payload = {'model': CHAT_MODEL, 'messages': messages, 'stream': False,
               'temperature': temperature, 'max_tokens': max_tokens}
    r = requests.post(CHAT_API_URL,
                      headers={'Authorization': 'Bearer ' + token,
                               'Content-Type': 'application/json'},
                      data=json.dumps(payload), timeout=90)
    if r.status_code != 200:
        raise RuntimeError('chat API %d: %s' % (r.status_code, r.text[:200]))
    return (r.json()['choices'][0]['message'].get('content') or u'').strip()


CAT_NOUN = {'animals': 'animal', 'countries': 'country', 'cities': 'city'}


def gen_riddle(secret, category_noun, lang_name, token):
    """Ask the model for a child-friendly clue, three hints and the localized name."""
    sysp = ("You run a children's guessing game. The secret %s is '%s'. "
            "Respond ONLY with compact single-line JSON: "
            '{"clue": "two short child-friendly sentences describing it WITHOUT '
            'naming it", "hints": ["hint one", "hint two", "hint three"], '
            '"answer": "the name of the secret in the target language"} '
            "where the hints get progressively easier but never name it. "
            "Write clue and hints in %s." % (category_noun, secret, lang_name))
    out = chat([{'role': 'system', 'content': sysp},
                {'role': 'user', 'content': 'Generate now.'}],
               token, max_tokens=600, temperature=0.85)
    m = re.search(r'\{.*\}', out.replace('```json', '').replace('```', ''), re.S)
    if not m:
        raise RuntimeError('no JSON in riddle response: %s' % out[:150])
    d = json.loads(m.group(0))
    clue = d['clue'].strip()
    hints = [h.strip() for h in d.get('hints', [])][:3]
    answer = (d.get('answer') or secret).strip()
    return clue, hints, answer


def is_correct(secret, guess, lang_name, token):
    """Judge a guess, allowing translations / synonyms / small misspellings."""
    if secret.lower() in guess.lower():
        return True
    try:
        out = chat([{'role': 'system', 'content':
                     "You judge a children's guessing game. The correct answer is "
                     "'%s'. A child guessed: '%s'. Allowing %s names, synonyms and "
                     "small misspellings, is the guess essentially correct? "
                     "Answer with only the word YES or NO." % (secret, guess, lang_name)}],
                   token, max_tokens=200, temperature=0)
        # reasoning model: look for a yes/no anywhere in the (short) answer
        low = out.strip().lower()
        return low.startswith('y') or 'yes' in low[:20]
    except Exception:
        return False


def show_riddle_tablet(session, sftp_info, cat_label, main_text,
                       hint_label, skip_label, stop_label, exit_label):
    """Show the riddle screen with HINT, SKIP, STOP and EXIT buttons on the
    tablet.

    The buttons use qimessaging.js to write to ALMemory[HINT_KEY / SKIP_KEY /
    STOP_KEY / EXIT_KEY]; the game loop polls those keys. Returns False if
    the tablet is down.
    """
    try:
        tablet = session.service('ALTabletService')
    except Exception:
        return False
    html = (
        u'<!doctype html><html><head><meta charset="utf-8">'
        u'<meta name="viewport" content="width=device-width,initial-scale=1">'
        u'<style>html,body{height:100%%;margin:0}'
        u'body{display:flex;flex-direction:column;justify-content:center;'
        u'align-items:center;background:#3d2b7a;color:#fff;'
        u'font-family:Arial,Helvetica,sans-serif;text-align:center;padding:4%%}'
        u'.cat{font-size:5vw;letter-spacing:.3vw;opacity:.8;margin-bottom:3vh}'
        u'.main{font-size:6.5vw;font-weight:bold;line-height:1.25;margin-bottom:6vh}'
        u'.btns{display:flex;flex-wrap:wrap;justify-content:center;gap:3vw}'
        u'button{font-size:4.6vw;font-weight:bold;border:none;border-radius:4vw;'
        u'padding:2.6vh 5vw}button:active{transform:translateY(1vh);box-shadow:none!important}'
        u'#hb{color:#3d2b7a;background:#ffd23f;box-shadow:0 1vh 0 #c99a00}'
        u'#sb{color:#fff;background:#6b5aa8;box-shadow:0 1vh 0 #473b73}'
        u'#tb{color:#fff;background:#c0392b;box-shadow:0 1vh 0 #7d2016}'
        u'#eb{color:#fff;background:#555b6e;box-shadow:0 1vh 0 #33373f}'
        u'</style><script src="qimessaging.js"></script></head><body>'
        u'<div class="cat">%s</div><div class="main">%s</div>'
        u'<div class="btns"><button id="hb" onclick="tap(\'hb\',\'%s\')">%s</button>'
        u'<button id="sb" onclick="tap(\'sb\',\'%s\')">%s</button>'
        u'<button id="tb" onclick="tap(\'tb\',\'%s\')">%s</button>'
        u'<button id="eb" onclick="tap(\'eb\',\'%s\')">%s</button></div>'
        u'<script>var M=null;'
        u'function conn(){try{QiSession(function(s){var p=s.service("ALMemory");'
        u'var set=function(m){M=m;};if(p.then)p.then(set);else if(p.done)p.done(set);},'
        u'function(){setTimeout(conn,2000);});}catch(e){setTimeout(conn,2000);}}conn();'
        u'function tap(id,key){if(M){M.insertData(key,Date.now());}'
        u'var b=document.getElementById(id);var t=b.textContent;b.textContent="...";'
        u'setTimeout(function(){b.textContent=t;},1200);}</script>'
        u'</body></html>'
    ) % (_esc(cat_label), _esc(main_text), HINT_KEY, _esc(hint_label),
         SKIP_KEY, _esc(skip_label), STOP_KEY, _esc(stop_label),
         EXIT_KEY, _esc(exit_label))
    try:
        ssh, sftp = sftp_info
        f = sftp.open(REMOTE_HTML, 'w')
        f.write(html.encode('utf-8'))
        f.close()
        url = 'http://198.18.0.1/guess.html?%d' % int(time.time())
        try:
            tablet.showWebview(url)
        except Exception:
            tablet.loadUrl(url)
            tablet.showWebview()
        return True
    except Exception as err:
        print('tablet display skipped (%s)' % err)
        return False


def main():
    parser = argparse.ArgumentParser(description='Pepper guessing (riddle) game.')
    parser.add_argument('-ip', '--ip', type=str, default='192.168.137.214')
    parser.add_argument('-port', '--port', type=int, default=NAOQI_PORT)
    parser.add_argument('-ssh_port', '--ssh_port', type=int, default=22)
    parser.add_argument('-u', '--username', type=str, default='nao')
    parser.add_argument('-p', '--password', type=str,
                        default=os.environ.get(PEPPER_PW_ENV_VAR),
                        help='Pepper ssh password (or set %s)' % PEPPER_PW_ENV_VAR)
    parser.add_argument('-d', '--duration', type=int, default=5,
                        help='seconds to record each guess')
    parser.add_argument('-l', '--lang', type=str, default='en', choices=['en', 'de'])
    parser.add_argument('-c', '--category', type=str, default='mixed',
                        choices=['animals', 'countries', 'cities', 'mixed'])
    parser.add_argument('-a', '--attempts', type=int, default=5,
                        help='wrong guesses allowed before the answer is revealed')
    parser.add_argument('-r', '--rounds', type=int, default=0,
                        help='number of items (0 = endless until Ctrl+C)')
    parser.add_argument('-ra', '--remote_audio_path', type=str,
                        default='/home/nao/recording.wav')
    parser.add_argument('-la', '--local_audio_path', type=str,
                        default='./recording.wav')
    parser.add_argument('--kiosk', action='store_true',
                        help='internal: set when launched by the tablet kiosk menu '
                             '(so EXIT does not spawn a second kiosk process)')
    args = parser.parse_args()

    if not STT_BASE_URL:
        print('ERROR: set the %s environment variable first.' % BASE_URL_ENV_VAR)
        print('  Windows:  set %s=https://your-open-webui-server'
              % BASE_URL_ENV_VAR)
        sys.exit(1)
    token = os.environ.get(TOKEN_ENV_VAR)
    if not token:
        print('ERROR: set the %s environment variable first.' % TOKEN_ENV_VAR)
        sys.exit(1)
    if not args.password:
        print('ERROR: set the %s environment variable, or pass -p <password>.'
              % PEPPER_PW_ENV_VAR)
        sys.exit(1)

    ph = PHRASES[args.lang]

    ip = find_pepper(args.ip)
    if not ip:
        print('could not find Pepper on the %s.x network.' % HOTSPOT_SUBNET)
        sys.exit(1)

    session = qi.Session()
    try:
        session.connect('tcp://%s:%d' % (ip, args.port))
    except RuntimeError:
        print('cannot connect to Pepper at %s:%d' % (ip, args.port))
        sys.exit(1)
    print('connected to Pepper at %s:%d' % (ip, args.port))

    tts = session.service('ALTextToSpeech')
    tts.setLanguage(ph['tts'])
    try:
        memory = session.service('ALMemory')
        memory.insertData(HINT_KEY, 0)
        memory.insertData(SKIP_KEY, 0)
        memory.insertData(STOP_KEY, 0)
        memory.insertData(EXIT_KEY, 0)
    except Exception:
        memory = None

    sftp_info = None
    try:
        import paramiko
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(ip, args.ssh_port, args.username, args.password, timeout=10)
        sftp_info = (ssh, ssh.open_sftp())
    except Exception as err:
        print('note: tablet uploads disabled (%s)' % err)

    def read_int(key):
        if not memory:
            return 0
        try:
            return int(memory.getData(key))
        except Exception:
            return 0

    categories = ['animals', 'countries', 'cities'] if args.category == 'mixed' \
        else [args.category]
    recent = []
    base_stop = read_int(STOP_KEY)
    base_exit = read_int(EXIT_KEY)

    def quit_requested():
        return read_int(STOP_KEY) > base_stop or read_int(EXIT_KEY) > base_exit

    tts.say(ph['welcome'])

    rounds = 0
    quit_game = False
    try:
        while not quit_game and (args.rounds == 0 or rounds < args.rounds):
            rounds += 1
            category = random.choice(categories)
            pool = [w for w in WORDS[category] if w not in recent] or WORDS[category]
            secret = random.choice(pool)
            recent = (recent + [secret])[-8:]
            print('\n=== round %d: %s = %s ===' % (rounds, category, secret))

            set_eyes(session, 0x00A000)
            tts.say(ph['think'])
            try:
                clue, hints, answer_label = gen_riddle(secret, CAT_NOUN[category],
                                                       ph['tts'], token)
            except Exception as err:
                print('riddle generation failed: %s' % err)
                rounds -= 1
                continue
            set_eyes(session, None)
            print('clue: %s' % clue.encode('utf-8'))

            cat_label = ph['cattab'][category]
            if sftp_info:
                show_riddle_tablet(session, sftp_info, cat_label, ph['tab_main'],
                                   ph['hint_btn'], ph['skip_btn'],
                                   ph['stop_btn'], ph['exit_btn'])
            last_hintreq = read_int(HINT_KEY)
            last_skipreq = read_int(SKIP_KEY)
            hint_idx = [0]

            def give_hint():
                if hint_idx[0] < len(hints):
                    tts.say(ph['hint_intro'])
                    tts.say(hints[hint_idx[0]].encode('utf-8'))
                    if sftp_info:
                        show_riddle_tablet(session, sftp_info, cat_label,
                                           hints[hint_idx[0]], ph['hint_btn'],
                                           ph['skip_btn'], ph['stop_btn'], ph['exit_btn'])
                    hint_idx[0] += 1
                else:
                    tts.say(ph['no_more_hints'])

            tts.say(clue.encode('utf-8'))

            solved = False
            skipped = False
            attempts_left = args.attempts
            while attempts_left > 0:
                # STOP/EXIT button -> quit the game (back to the menu if kiosked)
                if quit_requested():
                    quit_game = True
                    break
                # tablet buttons pressed since last check?
                if read_int(SKIP_KEY) > last_skipreq:
                    skipped = True
                    break
                cur = read_int(HINT_KEY)
                if cur > last_hintreq:
                    last_hintreq = cur
                    give_hint()
                    continue

                set_eyes(session, 0x0000FF)
                # poll_fn lets tablet buttons interrupt the recording immediately
                aborted = record_audio(session, args.remote_audio_path, args.duration,
                                       cue=ph['guess_now'], poll_fn=quit_requested)
                set_eyes(session, None)
                if aborted or quit_requested():
                    quit_game = True
                    break
                download_audio(ip, args.ssh_port, args.username, args.password,
                               args.remote_audio_path, args.local_audio_path)
                guess = transcribe(args.local_audio_path, token, args.lang)

                # a tablet tap may have arrived during recording
                if quit_requested():
                    quit_game = True
                    break
                if read_int(SKIP_KEY) > last_skipreq:
                    skipped = True
                    break
                cur = read_int(HINT_KEY)
                if cur > last_hintreq:
                    last_hintreq = cur
                    give_hint()
                    continue

                alnum = [c for c in guess if c.isalnum()] if guess else []
                if len(alnum) < 2:
                    tts.say(ph['nothing'])
                    continue

                low = guess.lower()
                if any(w in low for w in ph['skipwords']):
                    skipped = True
                    break
                if any(w in low for w in ph['hintwords']):
                    give_hint()
                    continue

                if is_correct(secret, guess, ph['tts'], token):
                    solved = True
                    break
                attempts_left -= 1
                tts.say(ph['wrong'])

            if quit_game:
                break
            if solved:
                set_eyes(session, 0x00A000)
                tts.say(ph['correct'])
                tts.say((ph['reveal'] % answer_label).encode('utf-8'))
                if sftp_info:
                    show_on_tablet(session, sftp_info, ph['correct'], answer_label,
                                   bg='#1b7f4b', stop_label=ph['stop_btn'],
                                   exit_label=ph['exit_btn'])
            else:
                if skipped:
                    tts.say(ph['skip_intro'])
                tts.say((ph['reveal'] % answer_label).encode('utf-8'))
                if sftp_info:
                    show_on_tablet(session, sftp_info, u'', answer_label,
                                   bg='#b8860b', stop_label=ph['stop_btn'],
                                   exit_label=ph['exit_btn'])
            set_eyes(session, None)
            time.sleep(2)
        exited_via_menu = quit_game and read_int(EXIT_KEY) > base_exit
        if quit_game and sftp_info and not exited_via_menu:
            # STOP was tapped (not EXIT): leave the tablet on a neutral,
            # button-free screen instead of a frozen page with dead buttons
            show_on_tablet(session, sftp_info, u'', ph['goodbye'],
                           bg='#12203a', show_controls=False)
        tts.say(ph['goodbye'])
        if exited_via_menu and not args.kiosk:
            # EXIT was tapped and nothing else is going to bring the game
            # menu back (we were not launched by the kiosk) -- do it ourselves
            relaunch_kiosk_menu(ip)
    except KeyboardInterrupt:
        print('\nstopping game ...')
        try:
            tts.say(ph['goodbye'])
        except Exception:
            pass
    finally:
        set_eyes(session, None)
        if sftp_info:
            try:
                sftp_info[1].close(); sftp_info[0].close()
            except Exception:
                pass
    print('total items played: %d' % rounds)


if __name__ == '__main__':
    main()
